name: d7-php74

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - 'drupal/7/php74/base'
        tag:
          - 'd7-php74'
    steps:
    - uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        context: ${{ matrix.folder }}
        platforms: linux/amd64,linux/arm64
        file: '${{ matrix.folder }}/Dockerfile'
        tags: 'lawxen/drupal:${{ matrix.tag }}'
