ARG MY_PHP_VERSION
ARG MY_DRUPAL_VERSION
FROM lawxen/drupal:php${MY_PHP_VERSION}-alpine${MY_DRUPAL_VERSION}

########### DEV #############
# Install xdebug
# https://github.com/nvm-sh/nvm?tab=readme-ov-file#alpine-linux-313
RUN apk update \
  && apk add linux-headers \
  && rm -rf /var/cache/apk/*

ARG XDEBUG_VERSION
# Install xdebug
RUN pecl install xdebug${XDEBUG_VERSION} && docker-php-ext-enable xdebug

# Preemptively creates log files, and give them to www-data
RUN cd /var/log \
  && touch php_error.log xdebug.log \
  && chown 1001:1001 php_error.log xdebug.log

# Config Xdebug
RUN { \
  # echo "[xdebug]"; \
  echo "xdebug.mode=debug"; \
  echo "xdebug.client_host=host.docker.internal"; \
  echo "xdebug.discover_client_host=true"; \
  echo "xdebug.start_with_request=yes"; \
  echo "xdebug.log=/var/log/xdebug.log"; \
  # echo "xdebug.idekey=PHPSTORM"; \
  } >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# Install drupal coder and config it
RUN composer global require drupal/coder; \
    composer clear-cache

RUN { \
  echo "alias drupalcs=\"phpcs --standard=Drupal --extensions=\"php,module,inc,install,test,profile,theme,css,info,txt,md,yml\"\""; \
  echo "alias drupalcsp=\"phpcs --standard=DrupalPractice --extensions=\"php,module,inc,install,test,profile,theme,css,info,txt,md,yml\"\""; \
  echo "alias drupalcbf=\"phpcbf --standard=Drupal --extensions=\"php,module,inc,install,test,profile,theme,css,info,txt,md,yml\"\""; \
  } >> /root/.bashrc