name: drupal-debian

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - php: 'php7.4'
            tag: ['debian', 'debian-d9']
          - php: 'php8.2'
            tag: ['debian', 'debian-d10']
          - php: 'php8.3'
            tag: ['debian', 'debian-d10']
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: 'drupal/debian/${{ matrix.version.php }}/${{ matrix.version.tag }}/Dockerfile'
          tags: 'lawxen/drupal:${{ matrix.version.php }}-${{ matrix.version.tag }}'
