name: drupal-debian

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - TAG_FROM: 'php7.4-fpm'
            tag: 'php7.4-fpm'
          - TAG_FROM: 'php8.0-fpm'
            tag: 'php8.0-fpm'
          - TAG_FROM: 'php8.1-fpm'
            tag: 'php8.1-fpm'
          - TAG_FROM: 'php8.2-fpm'
            tag: 'php8.2-fpm'
          - TAG_FROM: 'php8.3-fpm'
            tag: 'php8.3-fpm'
          - TAG_FROM: '9-php8.1-fpm'
            KEEP_DRUPAL_FILES: 1
            tag: '9-php8.1-fpm'
          - TAG_FROM: '10-php8.3-fpm'
            KEEP_DRUPAL_FILES: 1
            tag: '10-php8.3-fpm'

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: "{{defaultContext}}:drupal"
          platforms: linux/amd64,linux/arm64
          file: 'alpine/Dockerfile.template'
          tags: 'lawxen/drupal:${{ matrix.version.tag }}'
          build-args: |
            TAG_FROM=${{ matrix.version.TAG_FROM }}
            KEEP_DRUPAL_FILES=${{ matrix.version.KEEP_DRUPAL_FILES }}
