name: drupal-debian-dev

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - BUILD_PHP_VERSION: '7.4'
            XDEBUG_VERSION: '-3.1.5'
            tag: 'php7.4-debian-dev'
          - BUILD_PHP_VERSION: '8.0'
            tag: 'php8.0-debian-dev'
          - BUILD_PHP_VERSION: '8.1'
            tag: 'php8.1-debian-dev'
          - BUILD_PHP_VERSION: '8.2'
            tag: 'php8.2-debian-dev'
          - BUILD_PHP_VERSION: '8.3'
            tag: 'php8.3-debian-dev'
          - BUILD_PHP_VERSION: '8.3'
            BUILD_DRUPAL_VERSION: '-d10'
            tag: 'php8.3-debian-d10-dev'

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: "{{defaultContext}}:drupal/debian"
          platforms: linux/amd64,linux/arm64
          file: 'Dockerfile-dev.template'
          tags: 'lawxen/drupal:${{ matrix.version.tag }}'
          build-args: |
            MY_PHP_VERSION=${{ matrix.version.BUILD_PHP_VERSION }}
            MY_DRUPAL_VERSION=${{ matrix.version.BUILD_DRUPAL_VERSION }}
            XDEBUG_VERSION=${{ matrix.version.XDEBUG_VERSION }}
