name: drupal-debian

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - BUILD_PHP_VERSION: '7.4'
            BUILD_DRUPAL_VERSION: '9'
            tag: 'php7.4-debian'
          - BUILD_PHP_VERSION: '8.0'
            BUILD_DRUPAL_VERSION: '9'
            tag: 'php8.0-debian'
          - BUILD_PHP_VERSION: '8.1'
            BUILD_DRUPAL_VERSION: '10'
            tag: 'php8.1-debian'
          - BUILD_PHP_VERSION: '8.2'
            BUILD_DRUPAL_VERSION: '10'
            tag: 'php8.2-debian'
          - BUILD_PHP_VERSION: '8.3'
            BUILD_DRUPAL_VERSION: '10'
            tag: 'php8.3-debian'
          - BUILD_PHP_VERSION: '8.3'
            BUILD_DRUPAL_VERSION: '10'
            KEEP_DRUPAL_FILES: 1
            tag: 'php8.3-debian-d10'

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: drupal/debian
          platforms: linux/amd64,linux/arm64
          file: 'Dockerfile.template'
          tags: 'lawxen/drupal:${{ matrix.version.tag }}'
          build-args: |
            MY_PHP_VERSION=${{ matrix.version.BUILD_PHP_VERSION }}
            MY_DRUPAL_VERSION=${{ matrix.version.BUILD_DRUPAL_VERSION }}
            KEEP_DRUPAL_FILES=${{ matrix.version.KEEP_DRUPAL_FILES }}
