name: drupal-alpine-oci8

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - TAG_FROM: "php8.3-fpm-alpine"
            tag: "php8.3-fpm-alpine-oci8"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: "{{defaultContext}}:drupal"
          platforms: linux/amd64
          file: "alpine.oci8.Dockerfile"
          tags: "lawxen/drupal:${{ matrix.version.tag }}"
          build-args: |
            TAG_FROM=${{ matrix.version.TAG_FROM }}
      - name: Login to ALIYUN CR
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          push: true
          context: "{{defaultContext}}:drupal"
          platforms: linux/amd64
          file: "alpine.oci8.Dockerfile"
          tags: "registry.cn-hangzhou.aliyuncs.com/lawxen/drupal:${{ matrix.version.tag }}"
          build-args: |
            TAG_FROM=${{ matrix.version.TAG_FROM }}