name: drupal-alpine

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - folder: 'php7.4/alpine'
            tag: 'php7.4-alpine'
          - folder: 'php7.4/alpine-d9'
            tag: 'php7.4-alpine-d9'
          - folder: 'php8.2/alpine'
            tag: 'php8.2-alpine'
          - folder: 'php8.2/alpine-d10'
            tag: 'php8.2-alpine-d10'
          - folder: 'php8.3/alpine'
            tag: 'php8.3-alpine'
          - folder: 'php8.3/alpine-d10'
            tag: 'php8.3-alpine-d10'

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: 'drupal/alpine/${{ matrix.version.folder }}/Dockerfile'
          tags: 'lawxen/drupal:${{ matrix.version.tag }}'
